steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/nprocess-api-prod:latest', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/nprocess-api-prod:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nprocess-api-prod'
      - '--image=gcr.io/${PROJECT_ID}/nprocess-api-prod:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=nprocess-api-prod@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-env-vars=GCP_PROJECT_ID=${PROJECT_ID},GOOGLE_CLOUD_PROJECT=${PROJECT_ID},APP_ENV=production,VERTEX_AI_LOCATION=us-central1,VERTEX_AI_MODEL=gemini-1.5-pro-002,FIRESTORE_DATABASE=(default),LOG_LEVEL=INFO,CORS_ORIGINS=https://nprocess.ness.com.br'
      - '--update-secrets=GEMINI_API_KEY=nprocess-gemini-api-key:latest'
images:
  - 'gcr.io/${PROJECT_ID}/nprocess-api-prod:latest'
